spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cebooklub_rewind
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/schema

  web:
    locale: en_PH
    locale_resolver: fixed
  thymeleaf:
    cache: false

server:
  port: 8082

cloudfront:
  url: https://ddoo2mtjx0c7b.cloudfront.net/cebooklub/

logging:
  level:
    org.springframework: DEBUG
    org.mybatis: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
#    jdbc.sqltiming: DEBUG
